### PR TITLE
Adopt CircleCI instead of Travis

### PR DESCRIPTION
**Pull request by aldesantis**

### CODE REVIEW

**Comment by aldesantis** [comment]
Not sure why the CircleCI is not showing up here, but here's the build: https://circleci.com/gh/aldesantis/solidus_paypal_braintree/10.

**Comment by kennyadsl** [comment]
Ci status can be seen here: https://circleci.com/gh/aldesantis/solidus_paypal_braintree

**Comment by cedum** [comment]
Continuing the work on the specs here: https://github.com/cedum/solidus_paypal_braintree/tree/circleci
Got it to a green state. Cleaning up and DRYing it a bit and should be ready to be merged back here.

**Comment by aldesantis** [comment]
Thanks @cedum for the help here!

**Comment by cedum** [comment]
I'm working separately on the two skipped PayPal feature specs (I'll create a separate PR). They seem to be outdated and even when failing they were dynamically marked as pending, hence testing nothing.

**Pull request merged**
