### PR TITLE
Add API partial for SolidusPayPalBraintree payments

### PR DESCRIPTION
**Pull request by mdesantis**

### CODE REVIEW

**Comment by kennyadsl** [comment]
@mdesantis what's the state of this PR?

**Comment by mamhoff** [comment]
Adding a :+1: here, it would :100: if this could be moved to a full PR and merged.

**Comment by mdesantis** [comment]
Hey guys, sorry for the delay :-/ at the moment I don't have time to work on this PR, feel free to take it

**Comment by kennyadsl** [comment]
This was fixed with https://github.com/solidusio/solidus_paypal_braintree/pull/270. Thanks @mdesantis!

**Pull request closed without merging**
