### PR TITLE
Update PayPal configuration instructions

### PR DESCRIPTION
**Pull request by kennyadsl**
Add needed PayPal configuration to make this extension work into the README.

### CODE REVIEW

**Comment by kennyadsl** [comment]
Yes, it worked for me. Anyway I'm ok removing the validation since we've spent something like one day to understand that this option was causing the issue. 

I'd leave the README change anyway, as instructions about how to let PayPal return the phone back to Solidus.

If you do agree I can change the last sentence and rebase against master, let me know!

**Comment by alepore** [comment]
@kennyadsl i tried again with a new sandbox and this seems to work, so yeah, i would merge this because it's important. A plain solidus install will not work without this setup.

**Comment by kennyadsl** [comment]
@tvdeyen done!

**Comment by alepore** [comment]
@kennyadsl rebase pls

**Comment by kennyadsl** [comment]
Sad sad

**Pull request merged**
