### PR TITLE
Fix deprecated solidus_gem_version references

### PR DESCRIPTION
**Pull request by pelargir**
SolidusSupport.solidus_gem_version is deprecated and will be removed in solidus_support 1.0

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]

**Comment by kennyadsl** [comment]
@pelargir hey thanks for the PR and sorry for the long wait. I think some of those have been fixed, can you please reabase?

**Comment by pelargir** [comment]
@kennyadsl thanks. Rebased and closed. And yes, it's rather frustrating that this PR was effectively supplanted by #261 which had been opened nearly a month later. Anything I can do in the future to get a PR noticed faster? I hate submitting a PR only to have the same work repeated by someone else.

**Comment by kennyadsl** [comment]
Hey @pelargir, sorry to hear that 😞. Please ping me next time there's a slow response on your PRs. Also, if you care about this gem, we are always looking for extensions maintainers if you want to contribute to helping us reviewing incoming PRs.

**Comment by pelargir** [comment]
Thanks @kennyadsl I'll be sure to do that. What is the process for becoming a maintainer? I'd be happy to help in any way I can. The project I'm working on right now relies on this gem for our checkout.

**Comment by kennyadsl** [comment]
There's no official process but if someone has time to help we can make them a maintainer. If you are interested you could start by just helping us reviewing incoming PRs and issues. After an initial period of that, we will give you all the permission needed to also merge and release new versions. Does it work?

**Pull request closed without merging**
