### PR TITLE
Make use of data collector in JS configurable

### PR DESCRIPTION
**Pull request by mamhoff**
Some stores do not want or need to do invasive fraud protection. For
these, it should be possible to turn data collection off without
overwriting partials.

### CODE REVIEW

**Comment by mamhoff** [comment]
What about we go ahead with this for now and create the configuration object once #236 is merged?

**Comment by tvdeyen** [comment]
@mamhoff agree. #236 has now been merged.

**Comment by kennyadsl** [comment]
Hey @mamhoff, I think this needs to be revisited after #236, right?

**Comment by seand7565** [comment]
Hey @mamhoff - would you have time to update this PR? I know it's a year too late, but I'd like to have this merged in (minus the style stuff which was handled in #236) If not just let me know and I'll update this and create a new PR. Thanks!

**Comment by mamhoff** [comment]
@seand7565 I think this does the trick - sorry I took a bit longer :)

**Review by seand7565 — COMMENTED** [review]
This looks great, thanks! Just one thing - can you add something to the README about this option? Maybe under the PayPal section, something like:
`For fraud prevention, PayPal recommends using a data collector to collect device information, which we've included. You're able to turn off the PayPal data collector on the payment method options if you desire.`

**Comment by mamhoff** [comment]
@seand7565 Added the documentation!

**Review by seand7565 — APPROVED** [review]
Looks great, thanks!

**Comment by kennyadsl** [comment]
@mamhoff can you please rebase now that we have specs running against 3.0 as well? Thanks!

**Review by kennyadsl — APPROVED** [review]

**Review by tvdeyen — APPROVED** [review]
Now that Kount and braintree do not work together anymore this will most likely need to change soon. but for now this is ok.

**Pull request merged**
