### PR TITLE
Respect state configuration

### PR DESCRIPTION
**Pull request by digitalWestie**
Helps solve #93

### CODE REVIEW

**Comment by spaghetticode** [comment]
@digitalWestie can you squash the 4 commits into a single one? So we keep git history clean, thank you!

**Comment by digitalWestie** [comment]
@spaghetticode done :)

**Comment by tvdeyen** [comment]
Thanks for the contribution. Might be superseded by #237 that also has tests.

**Comment by digitalWestie** [comment]
Looks like #237 is a clean way of achieving this.

**Comment by tvdeyen** [comment]
@digitalWestie I agree, do you mind closing this? Thanks for contributing anyway :clap:

**Pull request closed without merging**
